import "../globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import Header from "../_components/header/header";
import Provider from "../_trpc/provider";

// nextAuth
import { getServerSession } from "next-auth/next";
import SessionProvider from "../_components/session/sessionProvider";
import { authOptions } from "@/server/api/auth";

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // TODO: add store selector for dark mode so you can add dark class if necessary

  const session = await getServerSession(authOptions);

  return (
    <html lang="en" className="dark">
      <body
        className={`${roboto.className} bg-zinc-100 text-zinc-950 dark:bg-zinc-950 dark:text-zinc-100 min-h-screen`}
      >
        <Provider>
          <SessionProvider session={session}>
            <>
              <Header />
              {children}
            </>
          </SessionProvider>
        </Provider>
      </body>
    </html>
  );
}
